# Generated by Django 5.2.7 on 2025-10-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timerecord",
            name="description",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
