# Generated by Django 5.2.7 on 2025-10-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_timerecord_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="timerecord",
            name="duration",
            field=models.IntegerField(default=0),
        ),
    ]
