# Generated by Django 5.2.7 on 2025-10-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_timerecord_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timerecord",
            name="activity",
            field=models.CharField(
                choices=[
                    ("work", "Работа"),
                    ("study", "Учеба"),
                    ("sport", "Спорт"),
                    ("rest", "Отдых"),
                    ("meal", "Еда"),
                    ("sleep", "Сон"),
                    ("reading", "Чтение"),
                    ("gaming", "Игры"),
                ],
                max_length=20,
            ),
        ),
    ]
